# This file is generated by Tools/genwrapper.py.
# It wraps the operators from the 'tiberate_ntt_ops' namespace.
# Do not edit!

import torch


def enter_ntt_radix2(
    a: list[torch.Tensor],
    Rs: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    psi: list[torch.Tensor],
    _2q: list[torch.Tensor],
    ql: list[torch.Tensor],
    qh: list[torch.Tensor],
    kl: list[torch.Tensor],
    kh: list[torch.Tensor],
) -> None:
    """
    Python wrapper for the 'tiberate_ntt_ops::enter_ntt_radix2' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    Rs: list[torch.Tensor]
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    psi: list[torch.Tensor]
    _2q: list[torch.Tensor]
    ql: list[torch.Tensor]
    qh: list[torch.Tensor]
    kl: list[torch.Tensor]
    kh: list[torch.Tensor]
    Returns:
        None
    """
    torch.ops.tiberate_ntt_ops.enter_ntt_radix2(
        a, Rs, even, odd, psi, _2q, ql, qh, kl, kh
    )


def ntt_radix2(
    a: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    psi: list[torch.Tensor],
    _2q: list[torch.Tensor],
    ql: list[torch.Tensor],
    qh: list[torch.Tensor],
    kl: list[torch.Tensor],
    kh: list[torch.Tensor],
) -> None:
    """
    Python wrapper for the 'tiberate_ntt_ops::ntt_radix2' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    psi: list[torch.Tensor]
    _2q: list[torch.Tensor]
    ql: list[torch.Tensor]
    qh: list[torch.Tensor]
    kl: list[torch.Tensor]
    kh: list[torch.Tensor]
    Returns:
        None
    """
    torch.ops.tiberate_ntt_ops.ntt_radix2(
        a, even, odd, psi, _2q, ql, qh, kl, kh
    )


def intt_radix2(
    a: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    psi: list[torch.Tensor],
    Ninv: list[torch.Tensor],
    _2q: list[torch.Tensor],
    ql: list[torch.Tensor],
    qh: list[torch.Tensor],
    kl: list[torch.Tensor],
    kh: list[torch.Tensor],
) -> None:
    """
    Python wrapper for the 'tiberate_ntt_ops::intt_radix2' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    psi: list[torch.Tensor]
    Ninv: list[torch.Tensor]
    _2q: list[torch.Tensor]
    ql: list[torch.Tensor]
    qh: list[torch.Tensor]
    kl: list[torch.Tensor]
    kh: list[torch.Tensor]
    Returns:
        None
    """
    torch.ops.tiberate_ntt_ops.intt_radix2(
        a, even, odd, psi, Ninv, _2q, ql, qh, kl, kh
    )


def intt_radix2_exit(
    a: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    psi: list[torch.Tensor],
    Ninv: list[torch.Tensor],
    _2q: list[torch.Tensor],
    ql: list[torch.Tensor],
    qh: list[torch.Tensor],
    kl: list[torch.Tensor],
    kh: list[torch.Tensor],
) -> None:
    """
    Python wrapper for the 'tiberate_ntt_ops::intt_radix2_exit' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    psi: list[torch.Tensor]
    Ninv: list[torch.Tensor]
    _2q: list[torch.Tensor]
    ql: list[torch.Tensor]
    qh: list[torch.Tensor]
    kl: list[torch.Tensor]
    kh: list[torch.Tensor]
    Returns:
        None
    """
    torch.ops.tiberate_ntt_ops.intt_radix2_exit(
        a, even, odd, psi, Ninv, _2q, ql, qh, kl, kh
    )


def intt_radix2_exit_reduce(
    a: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    psi: list[torch.Tensor],
    Ninv: list[torch.Tensor],
    _2q: list[torch.Tensor],
    ql: list[torch.Tensor],
    qh: list[torch.Tensor],
    kl: list[torch.Tensor],
    kh: list[torch.Tensor],
) -> None:
    """
    Python wrapper for the 'tiberate_ntt_ops::intt_radix2_exit_reduce' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    psi: list[torch.Tensor]
    Ninv: list[torch.Tensor]
    _2q: list[torch.Tensor]
    ql: list[torch.Tensor]
    qh: list[torch.Tensor]
    kl: list[torch.Tensor]
    kh: list[torch.Tensor]
    Returns:
        None
    """
    torch.ops.tiberate_ntt_ops.intt_radix2_exit_reduce(
        a, even, odd, psi, Ninv, _2q, ql, qh, kl, kh
    )


def intt_radix2_exit_reduce_signed(
    a: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    psi: list[torch.Tensor],
    Ninv: list[torch.Tensor],
    _2q: list[torch.Tensor],
    ql: list[torch.Tensor],
    qh: list[torch.Tensor],
    kl: list[torch.Tensor],
    kh: list[torch.Tensor],
) -> None:
    """
    Python wrapper for the 'tiberate_ntt_ops::intt_radix2_exit_reduce_signed' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    psi: list[torch.Tensor]
    Ninv: list[torch.Tensor]
    _2q: list[torch.Tensor]
    ql: list[torch.Tensor]
    qh: list[torch.Tensor]
    kl: list[torch.Tensor]
    kh: list[torch.Tensor]
    Returns:
        None
    """
    torch.ops.tiberate_ntt_ops.intt_radix2_exit_reduce_signed(
        a, even, odd, psi, Ninv, _2q, ql, qh, kl, kh
    )
