# This file is generated by Tools/genwrapper.py.
# It wraps the operators from the 'tiberate_const_pool' namespace.
# Do not edit!

from typing import Any
import torch


def read_constant_chunk(
    dummy: torch.Tensor, offset_bytes: int, count: int, dtype: Any, layout: int
) -> torch.Tensor:
    """
    Python wrapper for the 'tiberate_const_pool::read_constant_chunk' custom operator.

    Args:
    dummy: torch.Tensor
    offset_bytes: int
    count: int
    dtype: Any
    layout: int
    Returns:
        torch.Tensor
    """
    return torch.ops.tiberate_const_pool.read_constant_chunk(
        dummy, offset_bytes, count, dtype, layout
    )


def upload_tensor_list(
    tensor_list: list[torch.Tensor],
    offset_list: list[int],
    layout: int,
    device_id: int,
) -> None:
    """
    Python wrapper for the 'tiberate_const_pool::upload_tensor_list' custom operator.

    Args:
    tensor_list: list[torch.Tensor]
    offset_list: list[int]
    layout: int
    device_id: int
    Returns:
        None
    """
    torch.ops.tiberate_const_pool.upload_tensor_list(
        tensor_list, offset_list, layout, device_id
    )
