# This file is generated by Tools/genwrapper.py.
# It wraps the operators from the 'tiberate_csprng_ops' namespace.
# Do not edit!

import torch


def chacha20(input: list[torch.Tensor], step: int) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_csprng_ops::chacha20' custom operator.

    Args:
    input: list[torch.Tensor]
    step: int
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_csprng_ops.chacha20(input, step)


def discrete_gaussian(
    input: list[torch.Tensor], btree_ptr: int, btree_size: int, depth: int
) -> None:
    """
    Python wrapper for the 'tiberate_csprng_ops::discrete_gaussian' custom operator.

    Args:
    input: list[torch.Tensor] (modified in-place)
    btree_ptr: int
    btree_size: int
    depth: int
    Returns:
        None
    """
    torch.ops.tiberate_csprng_ops.discrete_gaussian(
        input, btree_ptr, btree_size, depth
    )


def discrete_gaussian_fast(
    input: list[torch.Tensor],
    btree_ptr: int,
    btree_size: int,
    depth: int,
    step: int,
) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_csprng_ops::discrete_gaussian_fast' custom operator.

    Args:
    input: list[torch.Tensor]
    btree_ptr: int
    btree_size: int
    depth: int
    step: int
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_csprng_ops.discrete_gaussian_fast(
        input, btree_ptr, btree_size, depth, step
    )


def randint(input: list[torch.Tensor], q_ptrs: list[int]) -> None:
    """
    Python wrapper for the 'tiberate_csprng_ops::randint' custom operator.

    Args:
    input: list[torch.Tensor] (modified in-place)
    q_ptrs: list[int]
    Returns:
        None
    """
    torch.ops.tiberate_csprng_ops.randint(input, q_ptrs)


def randint_fast(
    input: list[torch.Tensor], q_ptrs: list[int], shift: int, step: int
) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_csprng_ops::randint_fast' custom operator.

    Args:
    input: list[torch.Tensor]
    q_ptrs: list[int]
    shift: int
    step: int
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_csprng_ops.randint_fast(
        input, q_ptrs, shift, step
    )


def randround(
    input: list[torch.Tensor], rand_bytes: list[torch.Tensor]
) -> None:
    """
    Python wrapper for the 'tiberate_csprng_ops::randround' custom operator.

    Args:
    input: list[torch.Tensor]
    rand_bytes: list[torch.Tensor] (modified in-place)
    Returns:
        None
    """
    torch.ops.tiberate_csprng_ops.randround(input, rand_bytes)
