import argparse
import os
import re
import subprocess
import sys
from textwrap import dedent, indent

import torch

CPP_TO_PYTHON_TYPE_MAP = {
    "Tensor[][]": "list[list[torch.Tensor]]",
    "Tensor[]": "list[torch.Tensor]",
    "Tensor": "torch.Tensor",
    "int": "int",
    "int[]": "list[int]",
    "int64_t": "int",
    "int64_t[]": "list[int]",
    "float": "float",
    "float[]": "list[float]",
    "bool": "bool",
    "str": "str",
    "()": "None",
}


def get_current_python_tag():
    """Return the Python ABI tag like 'cpython-312' for the current interpreter."""
    return f"cpython-{sys.version_info.major}{sys.version_info.minor}"


def generate_wrappers_from_dict(schemas: dict[str, list[str]], output_dir: str):
    """Generates individual Python wrapper files for each namespace."""
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    for namespace, ops_list in schemas.items():
        generated_code = [
            dedent(
                f"""
        # This file is generated by Tools/genwrapper.py.
        # It wraps the operators from the '{namespace}' namespace.
        # Do not edit!

        from typing import Any
        import torch
        """
            )
        ]
        for op_line in ops_list:
            match = re.match(r"(\w+)\s*\((.*)\)\s*->\s*(.*)", op_line)
            if not match:
                continue

            op_name, args_str, return_type_str = match.groups()

            parsed_args, arg_names, in_place_args = [], [], []
            if args_str:
                for arg_part in args_str.split(','):
                    arg_part = arg_part.strip()
                    is_inplace = "(a!)" in arg_part
                    if is_inplace:
                        arg_part = arg_part.replace("(a!)", "").strip()
                    parts = arg_part.split()
                    if not parts:
                        continue
                    arg_name = parts[-1]
                    cpp_type = " ".join(parts[:-1])
                    python_type = CPP_TO_PYTHON_TYPE_MAP.get(cpp_type, "Any")
                    parsed_args.append(f"{arg_name}: {python_type}")
                    arg_names.append(arg_name)
                    if is_inplace:
                        in_place_args.append(arg_name)

            python_return_type = CPP_TO_PYTHON_TYPE_MAP.get(
                return_type_str.strip(), "Any"
            )
            args_formatted = ", ".join(parsed_args)
            func_signature = (
                f"def {op_name}({args_formatted}) -> {python_return_type}:"
            )

            docstring_args = ""
            for arg_def in parsed_args:
                arg_name_doc = arg_def.split(":")[0]
                is_inplace_note = (
                    " (modified in-place)"
                    if arg_name_doc in in_place_args
                    else ""
                )
                docstring_args += f"    {arg_name_doc}: {arg_def.split(':')[1].strip()}{is_inplace_note}\n"
            docstring = f'''"""\n    Python wrapper for the '{namespace}::{op_name}' custom operator.\n\n    Args:\n{docstring_args.rstrip()}\n    Returns:\n        {python_return_type}\n    """'''

            call_args = ", ".join(arg_names)
            func_body = f"return torch.ops.{namespace}.{op_name}({call_args})"
            if python_return_type == "None":
                func_body = func_body.replace("return ", "", 1)

            generated_code.append(
                "\n".join(
                    [
                        func_signature,
                        indent(docstring, "    "),
                        indent(func_body, "    "),
                    ]
                )
            )

        generated_code.append("\n")

        file_name = f"{namespace.replace('tiberate_', '')}.py"
        output_file = os.path.join(output_dir, file_name)
        with open(output_file, "w") as f:
            f.write("\n\n".join(generated_code))


def extract_namespace_and_ops(so_path: str) -> tuple[list[str], list[str]]:
    """Extracts operator schemas from a .so file."""
    try:
        strings_process = subprocess.run(
            ['strings', so_path], capture_output=True, text=True, check=True
        )
        stdout_text = strings_process.stdout

        namespace_matches = re.findall(
            r"^tiberate_.*$", stdout_text, re.MULTILINE
        )

        namespaces = [ns.strip() for ns in namespace_matches]

        op_name_pattern = re.compile(r"(\w+)\s*\(")
        op_names_found = set()

        lines = stdout_text.strip().splitlines()
        for line in lines:
            if " ->" in line:
                found_on_line = op_name_pattern.findall(line)
                op_names_found.update(found_on_line)
        return namespaces, sorted(op_names_found)
    except FileNotFoundError:
        print(
            "Error: 'strings' command not found. Please ensure it's in your system's PATH."
        )
    except subprocess.CalledProcessError as e:
        print(f"Error running 'strings' on {so_path}: {e}")
    except Exception as e:
        print(f"An unexpected error occurred while processing {so_path}: {e}")
    return {}


def genwarpper(args):
    """Main function to generate wrappers and __init__.py."""
    print(
        f"Generating wrappers for custom PyTorch ops in directory: {args.path}"
    )
    lib_dir = os.path.abspath(args.path)
    if not os.path.isdir(lib_dir):
        print(f"Error: Directory not found at '{lib_dir}'")
        return

    all_schemas = {}

    init_str = dedent(
        """
    # This file is generated by tiberate/libs/wrapper/genwrapper.py.
    # Do not edit!
    """
    ).strip()
    init_from_list = []
    init_all_list = []
    current_tag = get_current_python_tag()
    abi_pattern = re.compile(rf".*\.{current_tag}.*\.so$")
    for lib_file in os.listdir(lib_dir):
        if not lib_file.endswith(".so"):
            continue
        if not abi_pattern.search(lib_file) and f".{current_tag}" in lib_file:
            continue  # skip mismatched ABI tag
        else:
            lib_path = os.path.join(lib_dir, lib_file)
            if args.verbose:
                print(f"  -> Analyzing library: {lib_path}")
            torch.ops.load_library(lib_path)
            namespaces, ops = extract_namespace_and_ops(lib_path)
            namespace_ops_from_file = {}
            for namespace in namespaces:
                for op in ops:
                    # check if the op exists in the namespace
                    if hasattr(getattr(torch.ops, namespace, None), op):
                        namespace_ops_from_file[namespace] = [
                            *namespace_ops_from_file.get(namespace, []),
                            op,
                        ]
            for namespace, ops in namespace_ops_from_file.items():
                init_from_list.append(
                    f"from .{namespace.replace('tiberate_', '')} import {', '.join(ops)}"
                )
                init_all_list.extend(ops)

            schemas_from_file = {
                namespace: [
                    str(
                        getattr(getattr(torch.ops, namespace), op)._schemas['']
                    ).replace(f"{namespace}::", "")
                    for op in ops
                    if hasattr(getattr(torch.ops, namespace, None), op)
                ]
                for namespace, ops in namespace_ops_from_file.items()
            }
            if schemas_from_file:
                for namespace, ops in schemas_from_file.items():
                    if namespace not in all_schemas:
                        all_schemas[namespace] = []
                    all_schemas[namespace].extend(ops)

    if args.verbose:
        print("\nFound operator schemas:")
        for namespace, ops in all_schemas.items():
            print(f"\n  Namespace: {namespace}\n")
            for op in ops:
                print(f"    {op} ")

    if not all_schemas:
        print(
            "\nCould not find any operator schemas in the specified directory."
        )
        return

    generate_wrappers_from_dict(all_schemas, args.output)

    init_str += "\n\n" + "\n".join(init_from_list)
    init_str += "\n\n__all__ = [\n    "
    init_str += ",\n    ".join(f"'{op}'" for op in init_all_list)
    init_str += "\n]\n"
    init_file_path = os.path.join(args.output, "__init__.py")
    with open(init_file_path, "w") as init_file:
        init_file.write(init_str)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate type-hinted Python wrappers for custom PyTorch ops by analyzing .so files."
    )
    parser.add_argument(
        "--path",
        type=str,
        default="tiberate/libs/torchops",
        help="Path to the directory containing the PyTorch ops libraries.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose output for debugging.",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=str,
        default="tiberate/libs/wrapper",
        help="Directory to save the generated Python wrapper file.",
    )
    args = parser.parse_args()
    genwarpper(args)
