# This file is generated by Tools/genwrapper.py.
# It wraps the operators from the 'tiberate_he_ops' namespace.
# Do not edit!

import torch


def codec_rotate_make_unsigned_reduce_2q(
    a: list[torch.Tensor], perm: list[torch.Tensor], _2q: list[torch.Tensor]
) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_he_ops::codec_rotate_make_unsigned_reduce_2q' custom operator.

    Args:
    a: list[torch.Tensor]
    perm: list[torch.Tensor]
    _2q: list[torch.Tensor]
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_he_ops.codec_rotate_make_unsigned_reduce_2q(
        a, perm, _2q
    )


def create_switcher_divide_by_p(
    c: list[torch.Tensor], p: list[torch.Tensor], PiRi: list[list[torch.Tensor]]
) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_he_ops::create_switcher_divide_by_p' custom operator.

    Args:
    c: list[torch.Tensor]
    p: list[torch.Tensor]
    PiRi: list[list[torch.Tensor]]
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_he_ops.create_switcher_divide_by_p(c, p, PiRi)


def mont_mult_sum_many_3d(
    a: list[torch.Tensor],
    b: list[torch.Tensor],
    _2q: list[torch.Tensor],
    ql: list[torch.Tensor],
    qh: list[torch.Tensor],
    kl: list[torch.Tensor],
    kh: list[torch.Tensor],
) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_he_ops::mont_mult_sum_many_3d' custom operator.

    Args:
    a: list[torch.Tensor]
    b: list[torch.Tensor]
    _2q: list[torch.Tensor]
    ql: list[torch.Tensor]
    qh: list[torch.Tensor]
    kl: list[torch.Tensor]
    kh: list[torch.Tensor]
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_he_ops.mont_mult_sum_many_3d(
        a, b, _2q, ql, qh, kl, kh
    )


def pc_add_fused(
    ct_data: list[torch.Tensor], pt_data: list[torch.Tensor], sp_prime_len: int
) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_he_ops::pc_add_fused' custom operator.

    Args:
    ct_data: list[torch.Tensor]
    pt_data: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_he_ops.pc_add_fused(
        ct_data, pt_data, sp_prime_len
    )


def rescale_exact_rounding_fused(
    a: list[torch.Tensor],
    scales: list[torch.Tensor],
    rescaler: list[torch.Tensor],
    round_at: int,
    sp_prime_len: int,
) -> None:
    """
    Python wrapper for the 'tiberate_he_ops::rescale_exact_rounding_fused' custom operator.

    Args:
    a: list[torch.Tensor]
    scales: list[torch.Tensor]
    rescaler: list[torch.Tensor]
    round_at: int
    sp_prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_he_ops.rescale_exact_rounding_fused(
        a, scales, rescaler, round_at, sp_prime_len
    )


def rescale_non_exact_rounding_fused(
    a: list[torch.Tensor],
    scales: list[torch.Tensor],
    rescaler: list[torch.Tensor],
    sp_prime_len: int,
) -> None:
    """
    Python wrapper for the 'tiberate_he_ops::rescale_non_exact_rounding_fused' custom operator.

    Args:
    a: list[torch.Tensor]
    scales: list[torch.Tensor]
    rescaler: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_he_ops.rescale_non_exact_rounding_fused(
        a, scales, rescaler, sp_prime_len
    )


def switch_key_switch_later_part_extend(
    rns_len: int,
    state: torch.Tensor,
    l_enter: torch.Tensor,
    l_enter_start_offset: int,
    sp_prime_len: int,
) -> torch.Tensor:
    """
    Python wrapper for the 'tiberate_he_ops::switch_key_switch_later_part_extend' custom operator.

    Args:
    rns_len: int
    state: torch.Tensor
    l_enter: torch.Tensor
    l_enter_start_offset: int
    sp_prime_len: int
    Returns:
        torch.Tensor
    """
    return torch.ops.tiberate_he_ops.switch_key_switch_later_part_extend(
        rns_len, state, l_enter, l_enter_start_offset, sp_prime_len
    )
