# This file is generated by Tools/genwrapper.py.
# It wraps the operators from the 'tiberate_mont_ops' namespace.
# Do not edit!

import torch


def make_signed(a: list[torch.Tensor], sp_prime_len: int) -> None:
    """
    Python wrapper for the 'tiberate_mont_ops::make_signed' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    sp_prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_mont_ops.make_signed(a, sp_prime_len)


def make_unsigned(a: list[torch.Tensor], sp_prime_len: int) -> None:
    """
    Python wrapper for the 'tiberate_mont_ops::make_unsigned' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    sp_prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_mont_ops.make_unsigned(a, sp_prime_len)


def mont_add(
    a: list[torch.Tensor], b: list[torch.Tensor], sp_prime_len: int
) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_mont_ops::mont_add' custom operator.

    Args:
    a: list[torch.Tensor]
    b: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_mont_ops.mont_add(a, b, sp_prime_len)


def mont_add_legacy(
    a: list[torch.Tensor], b: list[torch.Tensor], _2q: list[torch.Tensor]
) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_mont_ops::mont_add_legacy' custom operator.

    Args:
    a: list[torch.Tensor]
    b: list[torch.Tensor]
    _2q: list[torch.Tensor]
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_mont_ops.mont_add_legacy(a, b, _2q)


def mont_add_many_3d(
    input: list[torch.Tensor], sp_prime_len: int
) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_mont_ops::mont_add_many_3d' custom operator.

    Args:
    input: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_mont_ops.mont_add_many_3d(input, sp_prime_len)


def mont_add_reduce_2q(
    a: list[torch.Tensor], b: list[torch.Tensor], sp_prime_len: int
) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_mont_ops::mont_add_reduce_2q' custom operator.

    Args:
    a: list[torch.Tensor]
    b: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_mont_ops.mont_add_reduce_2q(a, b, sp_prime_len)


def mont_enter(
    a: list[torch.Tensor],
    Rs: list[torch.Tensor],
    ql: list[torch.Tensor],
    qh: list[torch.Tensor],
    kl: list[torch.Tensor],
    kh: list[torch.Tensor],
) -> None:
    """
    Python wrapper for the 'tiberate_mont_ops::mont_enter' custom operator.

    Args:
    a: list[torch.Tensor]
    Rs: list[torch.Tensor]
    ql: list[torch.Tensor]
    qh: list[torch.Tensor]
    kl: list[torch.Tensor]
    kh: list[torch.Tensor]
    Returns:
        None
    """
    torch.ops.tiberate_mont_ops.mont_enter(a, Rs, ql, qh, kl, kh)


def mont_enter_Rs(a: list[torch.Tensor], sp_prime_len: int) -> None:
    """
    Python wrapper for the 'tiberate_mont_ops::mont_enter_Rs' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    sp_prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_mont_ops.mont_enter_Rs(a, sp_prime_len)


def mont_enter_Rs_scale(a: list[torch.Tensor], sp_prime_len: int) -> None:
    """
    Python wrapper for the 'tiberate_mont_ops::mont_enter_Rs_scale' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    sp_prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_mont_ops.mont_enter_Rs_scale(a, sp_prime_len)


def mont_enter_scalar(
    a: list[torch.Tensor], b: list[torch.Tensor], sp_prime_len: int
) -> None:
    """
    Python wrapper for the 'tiberate_mont_ops::mont_enter_scalar' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    b: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_mont_ops.mont_enter_scalar(a, b, sp_prime_len)


def mont_enter_scalar_reduce_2q(
    a: list[torch.Tensor], b: list[torch.Tensor], sp_prime_len: int
) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_mont_ops::mont_enter_scalar_reduce_2q' custom operator.

    Args:
    a: list[torch.Tensor]
    b: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_mont_ops.mont_enter_scalar_reduce_2q(
        a, b, sp_prime_len
    )


def mont_mult(
    a: list[torch.Tensor], b: list[torch.Tensor], sp_prime_len: int
) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_mont_ops::mont_mult' custom operator.

    Args:
    a: list[torch.Tensor]
    b: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_mont_ops.mont_mult(a, b, sp_prime_len)


def mont_reduce(a: list[torch.Tensor], sp_prime_len: int) -> None:
    """
    Python wrapper for the 'tiberate_mont_ops::mont_reduce' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    sp_prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_mont_ops.mont_reduce(a, sp_prime_len)


def mont_reduce_add_many_3d(
    input: list[torch.Tensor], sp_prime_len: int
) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_mont_ops::mont_reduce_add_many_3d' custom operator.

    Args:
    input: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_mont_ops.mont_reduce_add_many_3d(
        input, sp_prime_len
    )


def mont_sub(
    a: list[torch.Tensor], b: list[torch.Tensor], sp_prime_len: int
) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_mont_ops::mont_sub' custom operator.

    Args:
    a: list[torch.Tensor]
    b: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_mont_ops.mont_sub(a, b, sp_prime_len)


def mont_sub_reduce_2q(
    a: list[torch.Tensor], b: list[torch.Tensor], sp_prime_len: int
) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_mont_ops::mont_sub_reduce_2q' custom operator.

    Args:
    a: list[torch.Tensor]
    b: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_mont_ops.mont_sub_reduce_2q(a, b, sp_prime_len)


def reduce_2q(a: list[torch.Tensor], sp_prime_len: int) -> None:
    """
    Python wrapper for the 'tiberate_mont_ops::reduce_2q' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    sp_prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_mont_ops.reduce_2q(a, sp_prime_len)


def tile_unsigned(
    a: list[torch.Tensor], _2q: list[torch.Tensor]
) -> list[torch.Tensor]:
    """
    Python wrapper for the 'tiberate_mont_ops::tile_unsigned' custom operator.

    Args:
    a: list[torch.Tensor]
    _2q: list[torch.Tensor]
    Returns:
        list[torch.Tensor]
    """
    return torch.ops.tiberate_mont_ops.tile_unsigned(a, _2q)
