# This file is generated by Tools/genwrapper.py.
# It wraps the operators from the 'tiberate_ntt2_ops' namespace.
# Do not edit!

import torch


def enter_ntt_radix2(
    a: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    psi: list[torch.Tensor],
    sp_prime_len: int,
) -> None:
    """
    Python wrapper for the 'tiberate_ntt2_ops::enter_ntt_radix2' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    psi: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_ntt2_ops.enter_ntt_radix2(
        a, even, odd, psi, sp_prime_len
    )


def intt_radix2(
    a: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    ipsi: list[torch.Tensor],
    sp_prime_len: int,
) -> None:
    """
    Python wrapper for the 'tiberate_ntt2_ops::intt_radix2' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    ipsi: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_ntt2_ops.intt_radix2(a, even, odd, ipsi, sp_prime_len)


def intt_radix2_exit(
    a: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    ipsi: list[torch.Tensor],
    sp_prime_len: int,
) -> None:
    """
    Python wrapper for the 'tiberate_ntt2_ops::intt_radix2_exit' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    ipsi: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_ntt2_ops.intt_radix2_exit(
        a, even, odd, ipsi, sp_prime_len
    )


def intt_radix2_exit_reduce(
    a: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    ipsi: list[torch.Tensor],
    sp_prime_len: int,
) -> None:
    """
    Python wrapper for the 'tiberate_ntt2_ops::intt_radix2_exit_reduce' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    ipsi: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_ntt2_ops.intt_radix2_exit_reduce(
        a, even, odd, ipsi, sp_prime_len
    )


def intt_radix2_exit_reduce_signed(
    a: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    ipsi: list[torch.Tensor],
    sp_prime_len: int,
) -> None:
    """
    Python wrapper for the 'tiberate_ntt2_ops::intt_radix2_exit_reduce_signed' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    ipsi: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_ntt2_ops.intt_radix2_exit_reduce_signed(
        a, even, odd, ipsi, sp_prime_len
    )


def ntt_radix2(
    a: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    psi: list[torch.Tensor],
    sp_prime_len: int,
) -> None:
    """
    Python wrapper for the 'tiberate_ntt2_ops::ntt_radix2' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    psi: list[torch.Tensor]
    sp_prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_ntt2_ops.ntt_radix2(a, even, odd, psi, sp_prime_len)
