# This file is generated by Tools/genwrapper.py.
# It wraps the operators from the 'tiberate_ntt2_ops' namespace.
# Do not edit!

from typing import Any

import torch


def enter_ntt_radix2(
    a: list[torch.Tensor],
    Rs: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    psi: list[torch.Tensor],
    _2q: list[torch.Tensor],
    ql: list[torch.Tensor],
    qh: list[torch.Tensor],
    kl: list[torch.Tensor],
    kh: list[torch.Tensor],
    prime_len: int,
) -> None:
    """
    Python wrapper for the 'tiberate_ntt2_ops::enter_ntt_radix2' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    Rs: list[torch.Tensor]
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    psi: list[torch.Tensor]
    _2q: list[torch.Tensor]
    ql: list[torch.Tensor]
    qh: list[torch.Tensor]
    kl: list[torch.Tensor]
    kh: list[torch.Tensor]
    prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_ntt2_ops.enter_ntt_radix2(
        a, Rs, even, odd, psi, _2q, ql, qh, kl, kh, prime_len
    )


def intt_radix2(
    a: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    psi: list[torch.Tensor],
    Ninv: list[torch.Tensor],
    _2q: list[torch.Tensor],
    ql: list[torch.Tensor],
    qh: list[torch.Tensor],
    kl: list[torch.Tensor],
    kh: list[torch.Tensor],
) -> None:
    """
    Python wrapper for the 'tiberate_ntt2_ops::intt_radix2' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    psi: list[torch.Tensor]
    Ninv: list[torch.Tensor]
    _2q: list[torch.Tensor]
    ql: list[torch.Tensor]
    qh: list[torch.Tensor]
    kl: list[torch.Tensor]
    kh: list[torch.Tensor]
    Returns:
        None
    """
    torch.ops.tiberate_ntt2_ops.intt_radix2(
        a, even, odd, psi, Ninv, _2q, ql, qh, kl, kh
    )


def intt_radix2_exit(
    a: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    psi: list[torch.Tensor],
    Ninv: list[torch.Tensor],
    _2q: list[torch.Tensor],
    ql: list[torch.Tensor],
    qh: list[torch.Tensor],
    kl: list[torch.Tensor],
    kh: list[torch.Tensor],
) -> None:
    """
    Python wrapper for the 'tiberate_ntt2_ops::intt_radix2_exit' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    psi: list[torch.Tensor]
    Ninv: list[torch.Tensor]
    _2q: list[torch.Tensor]
    ql: list[torch.Tensor]
    qh: list[torch.Tensor]
    kl: list[torch.Tensor]
    kh: list[torch.Tensor]
    Returns:
        None
    """
    torch.ops.tiberate_ntt2_ops.intt_radix2_exit(
        a, even, odd, psi, Ninv, _2q, ql, qh, kl, kh
    )


def intt_radix2_exit_reduce(
    a: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    psi: list[torch.Tensor],
    Ninv: list[torch.Tensor],
    _2q: list[torch.Tensor],
    ql: list[torch.Tensor],
    qh: list[torch.Tensor],
    kl: list[torch.Tensor],
    kh: list[torch.Tensor],
) -> None:
    """
    Python wrapper for the 'tiberate_ntt2_ops::intt_radix2_exit_reduce' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    psi: list[torch.Tensor]
    Ninv: list[torch.Tensor]
    _2q: list[torch.Tensor]
    ql: list[torch.Tensor]
    qh: list[torch.Tensor]
    kl: list[torch.Tensor]
    kh: list[torch.Tensor]
    Returns:
        None
    """
    torch.ops.tiberate_ntt2_ops.intt_radix2_exit_reduce(
        a, even, odd, psi, Ninv, _2q, ql, qh, kl, kh
    )


def intt_radix2_exit_reduce_signed(
    a: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    psi: list[torch.Tensor],
    Ninv: list[torch.Tensor],
    _2q: list[torch.Tensor],
    ql: list[torch.Tensor],
    qh: list[torch.Tensor],
    kl: list[torch.Tensor],
    kh: list[torch.Tensor],
) -> None:
    """
    Python wrapper for the 'tiberate_ntt2_ops::intt_radix2_exit_reduce_signed' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    psi: list[torch.Tensor]
    Ninv: list[torch.Tensor]
    _2q: list[torch.Tensor]
    ql: list[torch.Tensor]
    qh: list[torch.Tensor]
    kl: list[torch.Tensor]
    kh: list[torch.Tensor]
    Returns:
        None
    """
    torch.ops.tiberate_ntt2_ops.intt_radix2_exit_reduce_signed(
        a, even, odd, psi, Ninv, _2q, ql, qh, kl, kh
    )


def ntt_radix2(
    a: list[torch.Tensor],
    even: list[torch.Tensor],
    odd: list[torch.Tensor],
    psi: list[torch.Tensor],
    _2q: list[torch.Tensor],
    ql: list[torch.Tensor],
    qh: list[torch.Tensor],
    kl: list[torch.Tensor],
    kh: list[torch.Tensor],
    prime_len: int,
) -> None:
    """
    Python wrapper for the 'tiberate_ntt2_ops::ntt_radix2' custom operator.

    Args:
    a: list[torch.Tensor] (modified in-place)
    even: list[torch.Tensor]
    odd: list[torch.Tensor]
    psi: list[torch.Tensor]
    _2q: list[torch.Tensor]
    ql: list[torch.Tensor]
    qh: list[torch.Tensor]
    kl: list[torch.Tensor]
    kh: list[torch.Tensor]
    prime_len: int
    Returns:
        None
    """
    torch.ops.tiberate_ntt2_ops.ntt_radix2(
        a, even, odd, psi, _2q, ql, qh, kl, kh, prime_len
    )


def read_constant_chunk(
    dummy: torch.Tensor, offset_bytes: int, count: int, dtype: Any, layout: int
) -> torch.Tensor:
    """
    Python wrapper for the 'tiberate_ntt2_ops::read_constant_chunk' custom operator.

    Args:
    dummy: torch.Tensor
    offset_bytes: int
    count: int
    dtype: Any
    layout: int
    Returns:
        torch.Tensor
    """
    return torch.ops.tiberate_ntt2_ops.read_constant_chunk(
        dummy, offset_bytes, count, dtype, layout
    )


def upload_tensor_list(
    tensor_list: list[torch.Tensor],
    offset_list: list[int],
    layout: int,
    device_id: int,
) -> None:
    """
    Python wrapper for the 'tiberate_ntt2_ops::upload_tensor_list' custom operator.

    Args:
    tensor_list: list[torch.Tensor]
    offset_list: list[int]
    layout: int
    device_id: int
    Returns:
        None
    """
    torch.ops.tiberate_ntt2_ops.upload_tensor_list(
        tensor_list, offset_list, layout, device_id
    )
